export const COMPONENTS = {
  BUTTON: "button",
  CARD: "card",
  CAROUSEL: "carousel",
  CHECKBOX: "checkbox",
  DIVIDER: "divider",
  HEADER: "header",
  ICON: "icon",
  IMAGE: "image",
  INPUT: "input",
  MODAL: "modal",
  SLIDER: "slider",
  TEXT: "text",
  VIEW: "view",
};
